### ISSUE TITLE
sensor.feedparser not found also after reset

### ISSUE THREAD

**Issue by mfabiani53** [custom-components/sensor.feedparser#2]
I followed the instructions to enable custom component and added the sensors in config file and the entries into ui-lovelace.yaml as indicated by instructiuons, but also after three resets i get always the following error:
2018-08-22 13:20:01 ERROR (Thread-9) [homeassistant.loader] Error loading custom_components.sensor.feedparser. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 94, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sensor/feedparser.py", line 12, in <module>
    import feedparser
ImportError: No module named 'feedparser'
2018-08-22 13:20:01 ERROR (Thread-9) [homeassistant.loader] Unable to find component sensor.feedparser

**Comment by ludeeus** [comment]
This is common during the first startup after adding a custom component, restart HA to fix it

**Comment by iantrich** [comment]
Worked with @mfabiani53 and we got the issue for the sensor resolved, I believe.

**Comment by simonblau** [comment]
Hey guys, 
i almost get the same error, could you tell us, what you have done to solve this?

Thank you very much

**Comment by iantrich** [comment]
You need to do a pip install of the feedparser module

**Comment by simonblau** [comment]
Good point, feedparser wasn't installed yet, but still get "Platform not found: sensor.feedparser" in raspberry terminal and "Entity not available: sensor.feedparser" in HA Frontend, but no more detailed Error in the log :/

What can I do or what do you need to help me?

**Comment by iantrich** [comment]
Try updating to 0.3

**Comment by khuongphp** [comment]
```
{
  "domain": "feedparser",
  "name": "Feedparser",
  "version": "0.1.5", // add this if your file are miss
  "documentation": "https://github.com/custom-components/feedparser/blob/master/README.md",
  "dependencies": [],
  "codeowners": ["@iantrich"],
  "requirements": ["feedparser==6.0.2"]
}
```
I found one case: If you use old version of feedparser, please update it to latest
